from .model_interface import ModelInterface
from .model_interface_image import ModelInterfaceImage
from .model_interface_pro import ModelInterfacePro
from .model_interface_small import ModelInterfaceSmall
from .model_interface_pro_hover import ModelInterfaceProHover
from .model_interface_ts import ModelInterfaceTs
from .model_interface_pseudo import ModelInterfacePseudo
from .model_interface_binary import ModelInterfaceBinary
from .model_interface_image_pro import ModelInterfaceImagePro
from .model_interface_both import ModelInterfaceBoth
from .model_interface_both_pro import ModelInterfaceBothPro
# from .model_interface_image_u2pl import ModelInterfaceImageU2pl
from .model_interface_both_similarity import ModelInterfaceBothSimilarity
from .model_interface_both_mutual import ModelInterfaceBothMutual