General:
    comment: 
    seed: 2023
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200 
    grad_acc: 2
    frozen_bn: False
    patience: 30
    server: test #train #test
    log_path: logs/

Data:
    dataset_name: featuretsbase_data
    label_dir: /data114_2/shaozc/SegDiff/dataset_csv/conic_107.csv
    image_size: 256
    dim:
      - 256
      - 256
      - 6048
    upsample_mode: bilinear
    label_ratio: 0.1

    feature_extractor:
        steps:
          - 50
          - 150
          - 250
        blocks:
          - 7
          - 8
          - 9
        model_path: /data114_2/shaozc/LiveCell/latent-diffusion-main/logs/2023-02-18T21-47-52_pannuke/checkpoints/epoch=000193.ckpt
        model_config: /data114_2/shaozc/LiveCell/latent-diffusion-main/configs/latent-diffusion/pannuke.yaml
        input_activations: False
        
    train_dataloader:
        batch_size: 5 
        num_workers: 8

    test_dataloader:
        batch_size: 5
        num_workers: 8

Model:
    name: AggregrateWSA
    num_class: 7
    feature_channels: 384
    image_channels: 128
    decode_channels: 128

Model_Feature:
    name: UNetFormer
    num_class: 7
    image_size: 256
    pretrained: /data114_2/shaozc/SegDiff/logs/scripts/conic_107/UNetFormer_0.1_789_aug_pannuke/epoch=139-val_IoU=0.4294.ckpt
    encoder_channels:
        - 1344
        - 1344
        - 672
    scale_factor:
        - 1
        - 2
        - 1
    resize_factor:
        - 8
        - 4
        - 4
    decode_channels: 128
    block_number: 3


Model_Image:
    name: FPN
    num_class: 7
    pretrained: /data114_2/shaozc/SegDiff/logs/scripts/conic_107/FPN_0.1_aug/epoch=167-val_IoU=0.4192.ckpt

Optimizer:
    opt: lookahead_radam
    lr: 0.002 # small learning rate
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001


Loss:
    base_loss: dice

