General:
    comment: 
    seed: 2023
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200 
    grad_acc: 2
    frozen_bn: False
    patience: 30
    server: test #train #test
    log_path: logs/

Data:
    dataset_name: featurebaseaug_data
    label_dir: /data111/shaozc/SegDiff/SegDiff/dataset_csv/monusac_42.csv
    image_size: 256
    dim:
      - 256
      - 256
      - 6048
    upsample_mode: bilinear
    label_ratio: 0.05

    feature_extractor:
        steps:
          - 50
          - 150
          - 250
        blocks:
          - 5
          - 6
          - 7
          - 8
          - 12
        model_path: /data111/shaozc/SegDiff/LiveCell/latent-diffusion-main/logs/2023-02-19T13-49-01_consep/checkpoints/epoch=000051.ckpt
        model_config: /data111/shaozc/SegDiff/LiveCell/latent-diffusion-main/configs/latent-diffusion/consep.yaml
        input_activations: False
        
    train_dataloader:
        batch_size: 24 
        num_workers: 8

    test_dataloader:
        batch_size: 24
        num_workers: 8

Model:
    name: FPN
    num_class: 5


Optimizer:
    opt: lookahead_radam
    lr: 0.001
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: dice

